# Send F2 key to a server via vncviewr
# rstart [path to vnc passwd-file (as generated by the vncpasswd(1) program)] [server ip]
# make sure that password file is available in the file /run/secrets/vncpassw

{
  lib,
  writeShellApplication,
  xvfb-run,
  tigervnc,
  xvkbd,
  procps,
}:
(writeShellApplication {
  name = "rstart";
  runtimeInputs = [ xvfb-run tigervnc xvkbd procps];
  text = builtins.readFile ./vnc.sh;
})
// {
  meta = with lib; {
    licenses = licenses.mit;
    platforms = platforms.all;
  };
}
