#!/usr/bin/env bash
# Send F2 key to a server via vncviewr
# need because lenovo servers withoout original lenovo RAM stop at bios and require manual F2 confirmation to start
# rstart [path to vnc passwd-file (as generated by the vncpasswd(1) program)] [server ip]

vncpassw="${1:-"/run/secrets/vncpassw"}"
server="${2:-"192.168.10.10"}"
cat "$vncpassw" | vncpasswd -f > /run/secrets/vncpasswenc
xvfb-run --server-num=1 --server-args="-screen 0 1024x768x16" vncviewer -AutoSelect=0 -FullColor=0 -LowColorLevel=0 -passwd /run/secrets/vncpasswenc "$server" -display :1 &>/dev/null &
sleep 5
xvkbd -text "\[F2]" -display :1 -window "Intel(r) AMT KVM - TigerVNC" &>/dev/null &
sleep 3
pix="$(pidof Xvfb)"
kill "$pix"