#!/run/current-system/sw/bin/bash
# Send F2 key to a server via vncviewr
# need because lenovo servers withoout original lenovo RAM stop at bios and require manual F2 confirmation to start
# rstart [path to vnc passwd-file (as generated by the vncpasswd(1) program)] [server ip]

vncpassw="${1:-"/run/secrets/vncpassw"}"
serverFilePath="${2:-"/run/secrets/server"}"

server=$( < "$serverFilePath")
< "$vncpassw" vncpasswd -f > /run/secrets/vncpasswenc
echo "$server"
echo "$vncpassw" 
xvfb-run --server-num=1 --server-args="-screen 0 1024x768x16" vncviewer -AutoSelect=0 -FullColor=0 -LowColorLevel=0 -passwd /run/secrets/vncpasswenc "$server" -display :1 &>/dev/null &
echo "xvfb-run running"
sleep 5
xvkbd -text "\[F2]" -display :1 -window "Intel(r) AMT KVM - TigerVNC" &>/dev/null &
echo "F2 key sent"
sleep 3
pix="$(pidof Xvfb)"
echo "Ending"
kill "$pix"